change = int(input("input change in cents: "))
toonie = int(change / 200)
loonie = int((change % 200) / 100)
quart = int((change % 100) / 25)
dime = int((change % 25) / 10)
nick = int(((change % 25) % 10) / 5)
penn = int(change % 5)
print(toonie, "toonie(s)")
print(loonie, "loonie(s)")
print(quart, "quarter(s)")
print(dime, "dime(s)")
print(nick, "nickel(s)")
print(penn, "pennies")
